Polymer/polymer-analyzer

lib/monomers.js
package.json

Adds .load() for help recursing inside _parseHTML and to provide a cleaner API for using monomers.
By breaking up the recursion inside .load(), all parse work is moved to the end of the current task using a setImmediate polyfill.

Add a setImmediate based .load() function to monomers for simpler API and recursion.

---

lib/ast-utils/js-parse.js
package.json

Parsing tests continue to pass.
The failure in safari has changed, but it seems to be core-asset related. I'll resolve in another PR.

Change to espree for parsing.

---

package.json

Only include runtime code used by node projects

Restrict published contents

---

lib/loader/fs-resolver.js
test/test.js

This allows for absolute urls with '/' to be resolved correctly.
Also fixes tests, which broke when the reorg occured for file loader

Make fs resolver root config a prefix

---

lib/analyzer.js

Deeper branches of siblings can "load" before the current import
TODO: add tests
Fixes #116 Import Traversal Ordering does not follow spec

Move check of "loaded" into the metadata promise

---

bower.json

As polymer is only distributed over bower (and zip files) it only makes sense to enable users to install hydrolysis over bower as well. 
Changes in bower.json simply make the package public (i.e. publishable) and define hydrolysis.js as the main file (attribute required in bower.json).

adapted for publishing on bower

---

package.json

since we are using wct, but did not have it defined in our dependencies npm test would error out unless a user had web-component-tester installed globally or had manually installed it locally.

🐐 Add missing wct dep

---

lib/loader/fs-resolver.js

This patch checks if the `local` path is an absolute path, and if so, does not prefix it with the `root` path.
`polylint` for example always supplies both, causing absolute paths to fail.
Since SublimeLinter mostly uses an input stream (not gotten it to work) or an absolute path, merging this would make PolymerLabs/polylint#22 a lot easier to accomplish.

Support absolute paths in FSResolver

---

lib/ast-utils/js-parse.js
test/js-parser.html
test/static/es6-support.js

Fixes #141 and possibly a lot more handling of ES6 features. Turns out that even enabling new features on espree isn't helpful because estraverse isn't aware of all the new AST node types. This change adds `fallback: 'iteration'` which tells estraverse to just iterate on the children of the unknown node.

Traverse unknown JS AST nodes, rather than error.

---

custom_typings/dom5.d.ts
src/analyzer.ts

Previous handling of external script files breaks the DOM
structure and creates invalid text nodes according to dom5.
This manipulates existing script element to maintain DOM
structure and creates a text node with dom5 method.
Fixes Polymer/hydrolysis#185

Properly manipulate script tags with external scripts

---

package.json

I think there was a typo (see PR [#215](https://github.com/Polymer/hydrolysis/pull/215/files#r54637233)).
Include hydrolysis.js (imported by hydrolysis.html) into the npm package.

Fix files for npm package

---

custom_typings/espree.d.ts
package.json
src/ast-utils/element-finder.ts
src/ast-utils/js-parse.ts
test/js-parser.html
test/static/es6-support.js

Add some escape routes for walking the tree without an element.
ES6 classes now play well with ES5 elements.
ES6 support caused any es5-defined elements to throw during parsing.

make es5 and es6 classes play nicely together.

---

.gitignore
.npmignore
custom_typings/main.d.ts
src/ast/event-descriptor.ts
src/ast/feature-descriptor.ts
src/ast/function-descriptor.ts
src/index.ts
tsconfig.json

With these changes, hydrolysis works properly in a downstream typescript
project when `npm link`ed in.

Fix our exported type definitions.

---

custom_typings/jsonschema.d.ts

Not sure how I missed these, it seemed like `tsc` came back clean.

Fix minor errors in jsonschema typings

---

gulpfile.js
package.json
test/mocha.opts

Tired of figuring out which javascript line was which typescript line when npm test failures happened so I'm adding sourcemap support.
Note: because we use gulp-typescript to incrementally build (it wont build if js file is newer than ts), you need to blow out your lib/ folder to have the maps generate if you're pulling this to existing clone.

Add sourcemap support to build and mocha

---

.travis.yml
custom_typings/main.d.ts
custom_typings/performance-now.d.ts
package.json
src/analyzer.ts
src/ast/document-descriptor.ts
src/perf/parse-all-benchmark.ts
src/perf/telemetry.ts
src/test/perf/telemetry_test.ts

Makes Document generation linear (was quadratic) by adding some simple indexes on kind and kind+identifier on the root document.
Before this change Document.makeRootDocument on all PolymerElements sources took 1500ms, after this it takes ~30ms.
Also adds a resolution benchmark runnable with `npm run benchmark`

Measure and improve resolution performance.

---

gulpfile.js

Perhaps in a recent version of gulp-typescript the typings files were no longer being output.  Either that or they were never output since switching to gulp-typescript.  (was that my bad when I added the sourcemaps support?)  I don't know... However, this makes them output.

Fix gulp build to generate the .d.ts files in lib/.

---

package.json
src/analyzer.ts
src/html/html-import-scanner.ts
src/html/html-style-scanner.ts
src/polymer/css-import-scanner.ts
src/test/analyzer_test.ts
src/test/html/html-import-scanner_test.ts
src/test/polymer/css-import-scanner_test.ts

- Created a new CssImportScanner and test suite.
- Include the new scanner in Analyzer's html document scanners list.
- Added a new Analyzer test.
Note: required for bundler to support css inlining.

Created a CssImportScanner to support deprecated, but still supported, polymer-specific <link rel="import" type="css"> imports.

---

custom_typings/main.d.ts
custom_typings/split.d.ts
package.json
src/editor-service/editor-server.ts
src/test/editor-service/editor-server-test.ts
src/test/editor-service/editor-service_test.ts

Useful for extending editors like Sublime Text that (for some reason) aren't written in Node and can't use the Node IPC interface. The protocol is the same, this just extends editor-service.ts to speak the same protocol also over stdin/stdout.

Add a stdin/stdout interface to editor-server.

---

.vscode/settings.json

Two small changes I made to get vscode set up on my machine:
- I sometimes need to dig into the lib folder to see the code that is being executed. Excluding the folder from the tree feels a lot like personal preference.
- added `"typescript.tsdk"` to always match the same version of typescript we use to build, lint, etc.
Is there a way to add personal, project-scoped preferences to vscode? You should still be able to exclude the lib folder if you personally would like to.
/cc @rictic @justinfagnani

Update vscode settings to be shared

---

src/demo/polymer-lint.ts

Missing `await` statement led to process exiting before errors get printed.
/cc @rictic

await on `warningPrinter.printWarnings()` in demo

---

package.json
src/analyzer.ts
src/css/css-document.ts
src/css/css-parser.ts
src/demo/polymer-lint.ts
src/html/html-document.ts
src/html/html-parser.ts
src/html/html-script-tag.ts
src/javascript/javascript-document.ts
src/javascript/javascript-parser.ts
src/json/json-document.ts
src/json/json-parser.ts
src/model/document.ts
src/model/element.ts
src/parser/document.ts
src/parser/parser.ts
src/test/analyzer_test.ts
src/test/scanning/scan_test.ts

Should make #320 much more feasible. `ParsedDocument.getSourceRange` should now just Do The Right Thing in all circumstances.
Parsed Documents are now aware of their location offsets from the moment that they're created, and all implementations of `getSourceRange` now automatically apply the appropriate location offsets (if any).

Put all responsibility of location offsets on ParsedDocument

---

src/model/element.ts
src/polymer/behavior-scanner.ts
src/polymer/behavior.ts
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/html-missing-behaviors.html

This shouldn't conflict with #330 but an additional PR will be needed so that we can push this warning onto the document itself, instead of throwing a `WarningCarryingException`.
/cc @rictic @justinfagnani

"behavior not found" errors are now WarningCarryingExceptions

---

src/html/html-document.ts
src/test/html/html-document_test.ts
src/test/static/source-ranges/html-complicated.html

SourceRange production was inaccurate `<zoidberg>`and you should feel inaccurate`</zoidberg>`.
- Added code to correct SourceRange calculations for multi-line nodes.
- Changed the way element nodes report SourceRanges now to include closing tag when present.
- When closing tag is not present, element nodes now report multi-line SourceRanges correctly.
- Added test file for html-document and source-ranges html fixture.

Accurate SourceRange production for ParsedHtmlDocument

---

src/test/warning/warning-printer_test.ts
src/warning/warning-printer.ts

This will let us print better lint errors, and it also proves useful in an upcoming set of tests.

Teach warning printer to print multi line warnings.

---

src/model/document.ts
src/polymer/behavior.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts
src/test/static/chained-missing-behavior/chained.html
src/test/static/chained-missing-behavior/index.html

`document.getWarnings()` will now return all warnings on both the document and features within the document. It takes an optional `deep` argument which can be used to filter out warnings on non-local features. This behaves similar to `document.getFeatures().`
This grants our editor plugins, build pipeline, and others a single interface for getting warnings from a given document.
/cc @justinfagnani @rictic @usergenic @garlicnation

document.getWarnings()

---

src/html/html-import-scanner.ts
src/html/html-script-scanner.ts
src/html/html-style-scanner.ts
src/polymer/css-import-scanner.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts
src/test/editor-service/editor-service_test.ts

* for import errors, underline just the url
* fix the error code for behavior-not-found
* use getUnderlinedText to test source ranges in getWarningsForFile

A few miscellaneous warning improvements.

---

src/model/document.ts
src/test/editor-service/editor-service_test.ts

`Document#getWarnings()` was returning duplicate warnings because of the way `this.warnings` and `feature.getWarnings()` apparently contained the same items.  I just put a guard against pushing existing warnings into the result array.  Separated commits so there's one that proves the dup.

Fix duplicate warnings

---

package.json

Bump version so linter can use fixed version of analyzer without the duplicate warnings.

Bumped version to 2.0.0-alpha.14

---

.vscode/settings.json
src/css/css-document.ts
src/editor-service/ast-from-source-position.ts
src/editor-service/editor-service.ts
src/editor-service/local-editor-service.ts
src/html/html-document.ts
src/javascript/javascript-document.ts
src/json/json-document.ts
src/parser/document.ts
src/test/editor-service/ast-from-source-position_test.ts
src/test/editor-service/editor-service_test.ts
src/test/html/html-document_test.ts
src/test/static/unclosed-tag-attributes.html

This fixes a bunch of bugs, including Polymer/atom-plugin#7 Polymer/atom-plugin#8 and Polymer/atom-plugin#9 as well as a *lot* of subtle edge cases that we weren't getting right.
There's probably more work to be done here, I didn't test any multiline use cases here, though I'm hoping that since this builds on #347 that most of that stuff should Just Work.
Also I made some methods protected that should have been (they were only ever intended to be defined or called by subclasses anyways).
/cc @TimvdLippe

Rewrite code for mapping source positions to HTML ASTs

---

src/polymer/analyze-properties.ts
src/test/polymer/polymer-element-scanner_test.ts

Fixes #350.
I also added a bunch of polymer-element tests so I was able to test that `readOnly` is set correctly.
I did pass through clang-format but if you think there's anything horrible going on in here, do review!
If you are wondering why I use an `isComputed` flag, it is to avoid tripping up on the following (also found in tests):
```javascript
{
computed: '_computeMe()',
readOnly: false
}
```
So it will still mark as `readOnly: true` instead of being mistakenly overridden by the property there. If this is wrong behaviour, do let me know.

mark computed props as readOnly

---

src/analyzer.ts
src/html/html-element-reference-scanner.ts
src/model/element-reference.ts
src/test/html/html-element-reference-scanner_test.ts
src/test/html/html-import-scanner_test.ts

This is far from complete but looking for feedback.
Essentially, this scanner will find custom element references (tags in the HTML document). This is a fairly useful scanner for something like polymer-linter to retrieve a full list of referenced custom elements.
I'm still getting my head around much of the analyser so forgive me if I make any obvious mistakes and such...
**What is the best way to populate `attributes` with the tag's attributes from parse5?**
I would like to populate the `attributes` property of `ElementReference` but I haven't quite figured out where I should do that, yet.
**Should the classes be prefixed with `Custom` and a base implementation added?**
Currently, we confusingly call it `ElementReference` but it is actually specific to _custom_ elements. Maybe we should …

Element reference scanner

---

src/model/document.ts
src/model/model.ts

Fixes #362.
I'm not sure if the export is correct in `model.ts`. I had to expose particular models because the `Attribute` clashes with Element's `Attribute`.

expose reference models correctly

---

.vscode/launch.json

Useful for debugging in .vscode. The debug "play" button should just work for all of us now, since it's using the mocha dependency of the analyzer itself.
/cc @justinfagnani  @rictic @usergenic

Add .vscode debugging launch script

---

package.json

node_modules/.bin is added to the npm run PATH automatically. (The runs for me without clang-format installed)
/cc @rictic

remove unneccesary node_modules/.bin path from package.json

---

.clang-format
src/analyzer.ts
src/editor-service/ast-from-source-position.ts
src/generate-elements.ts
src/html/html-document.ts
src/html/html-import-scanner.ts
src/html/html-script-scanner.ts
src/html/html-script-tag.ts
src/html/html-style-scanner.ts
src/javascript/javascript-document.ts
src/javascript/javascript-import-scanner.ts
src/javascript/jsdoc.ts
src/model/import.ts
src/polymer/css-import-scanner.ts
src/polymer/docs.ts
src/polymer/dom-module-scanner.ts
src/polymer/feature-scanner.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts
src/test/editor-service/ast-from-source-position_test.ts
src/test/editor-service/editor-service_test.ts
src/test/html/html-import-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/vanilla-custom-elements/element-scanner_test.ts

The formatting options introduced with #384 cause clang-format to produce invalid code with async methods whose signatures are a certain length. Specifically `BinPackParameters: false` will turn
```typescript
class C {
async method(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, b, c) {
}
}
```
into
```typescript
class C {
async
method(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, b, c) {
}
}
```
which is semantically different code. I would report a bug upstream but account creation in their bug tracker is disabled: https://llvm.org/bugs/enter_bug.cgi
Given this, I'm leaning towards the idea that future changes that affect formatting should also include the results of `npm run format`. There will be merge conflicts, but resolving them with the `ours` …

Format all code

---

CHANGELOG.md
src/analyzer.ts
src/css/css-parser.ts
src/html/html-parser.ts
src/javascript/javascript-parser.ts
src/json/json-parser.ts
src/model/document.ts
src/parser/document.ts
src/test/analyzer_test.ts
src/test/static/circular/mutual-a.html
src/test/static/circular/mutual-b.html
src/test/static/circular/self-import.html

This required two changes:
* break up scanning a document and its dependencies. cache the scanned document once it has been scanned but before its dependencies are.
* track a scanned document's inline status a bit better, and don't cache inline scanned documents. This was always a hidden error that was masked by the earlier order of operations.
Fixes #388

Handle mutually recursive import graphs.

---

CHANGELOG.md
src/model/element.ts
src/model/property.ts
src/polymer/polymer-element.ts
src/test/polymer/polymer-element-scanner_test.ts

Adds the notify field from the scanned properties to attribute.

Add notify field to Attribute

---

src/parser/document.ts
src/scanning/scan.ts
src/test/scanning/scan_test.ts

In a future version of node, this will kill the process, even though we've handled the error through other means.
(mea culpa: I think I asked for the promise to reject back when the scan() function was originally checked in)

Fix an unhandled promise rejection warning.

---

src/test/analyzer_test.ts
src/test/static/multiple-behavior-imports/behavior.html
src/test/static/multiple-behavior-imports/element-a.html
src/test/static/multiple-behavior-imports/element-b.html
src/utils.ts

The test is skipped for now, but it demonstrates that our caching strategy doesn't work properly with modifications of files coming in while other analyses are happening.
I believe this demonstrates the bug that's happening in https://github.com/Polymer/polymer-editor-service/issues/28

Add test that demonstrates issues with caching.

---

src/core/analysis-cache.ts
src/core/analyzer-cache-context.ts
src/core/async-work-cache.ts
src/test/core/analysis-cache_test.ts

This lets us remove the difficult-to-reason-about code (including the IIAFE with the immediate `await Promise.resolve()`) into one place where it can declare its invariants and be better maintained.

Manage async work caching in a class.

---

CHANGELOG.md
src/core/analyzer-cache-context.ts
src/polymer/docs.ts
src/polymer/polymer-element.ts
src/polymer/pseudo-element-scanner.ts
src/test/polymer/pseudo-element-scanner_test.ts

Adds support for extracting pseudo elements declared in comments via the `@pseudoElement` tag. (partially) fixes https://github.com/Polymer/polymer-analyzer/issues/187
Some notes:
* Only works for HTML comments for now. If you guys are happy with this, I'll add support for javascript comments as well.
* Right now the scanner extracts `ScannedPolymerElement`. We'll probably want to at least add a `pseudo` flag to mark elements as pseudo elements but a separate feature would probably be better. Maybe extend PolymerElement and add something like `pseudo-element` to the `kinds` set?
* I saw that there is already a [parsePseudoElements](https://github.com/Polymer/polymer-analyzer/blob/master/src/polymer/docs.ts#L292) function but it doesn't seem to be used anywhere yet. I copy/pasted some of …

Extract pseudo elements from comments

---

CHANGELOG.md
src/core/analysis-cache.ts
src/core/analyzer-cache-context.ts
src/test/analyzer_test.ts
src/test/core/analysis-cache_test.ts

We do take a ~100% hit to the benchmark, but that is a worst case scenario for this change (modifying the root of a very large import graph), and analysis is still only taking ~40ms.
It would still be nice if we could figure out a way to add something like this cache. There's no correctness issue with scanning dependencies multiple times, just a performance one, so we don't need the full power of getOrCompute. Hm. I think I have an idea for a followup PR that restores this performance win.

Fix an issue with parallel analysis of mutually importing documents.

---

package.json
src/test/url-loader/fs-url-loader_test.ts
src/url-loader/fs-url-loader.ts
tsconfig.json

It looks like the node v4 typings don't include definitions for `console` anymore? Seems like a bug, but moving to node v6 typings fixes.

Fix the build, option #1

---

CHANGELOG.md
src/core/analyzer-cache-context.ts
src/javascript/javascript-document.ts
src/javascript/javascript-parser.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/javascript/javascript-parser_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/vanilla-custom-elements/element-scanner_test.ts

This ensures that we don't throw parse errors for ES6 modules. We can't, in general, know at parse time whether a given bit of JS should be parsed as a module or a script.
I think, given that, it is better to parse robustly and just note whether a file must be a module, or that it is legal syntax as either a module or a script.
Fixes https://github.com/Polymer/polymer-editor-service/issues/12 and https://github.com/Polymer/vscode-plugin/issues/44
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/polymer/polymer-analyzer/428)

Improve ES6 module support.

---

src/analyzer.ts

This PR fixes a small typo in the API docs of the `Analyzer` class

analyzer: Fix typo

---

package.json
src/javascript/ast-value.ts
src/perf/parse-all-benchmark.ts
src/typescript/typescript-analyzer.ts

Installing the analyzer with `yarn` pulls in Typescript 2.2. This resulted in some compiler errors which I fixed all but one.
In TS 2.2 operators are more thoroughly checked, most notably arithmetic expressions do not allow undefined or null. I fixed these errors.
The last compiler error is because `lib.es2017.d.ts` in `typescript-analyzer.ts` pulls in `lib.es2016.d.ts` which pulls in `lib.es2015.d.ts` which pulls in `lib.es2015.collection.d.ts` and that file has a definition of `Map<K,V>`. This definition forces the second argument `value` of to be non-null per [this commit](https://github.com/Microsoft/TypeScript/commit/adedc1953b9a1136b5067f5224a3b4e7cd5b8956#diff-f7219547c512c7ed79bb415579ceb5afR27). I am not sure why the Typescript maintainers introduced this change, since on master …

Fix several compilation errors with Typescript 2.2

---

CHANGELOG.md
src/core/analysis-context.ts
src/html/html-script-tag.ts
src/model/import.ts

This fixes a TODO in the code. I am not 100% this is the correct fix, but given the comment regarding `resolve` I think this code should live in the `resolve` of `Import`. Note that since `html-script-tag` contains duplicate code, the same code is added twice. This can be fixed later I suppose.

Fix caching of warnings for failed scanning of imports

---

CHANGELOG.md
src/html/html-element-reference-scanner.ts
src/test/html/html-element-reference-scanner_test.ts

ReferenceScanner should descend into <template>s

---

src/test/editor-service/editor-service_test.ts
src/test/html/html-document_test.ts
src/test/html/html-element-reference-scanner_test.ts
src/test/test-utils.ts
src/test/typescript/typescript-preparser_test.ts

Previously this was awkward, but we want to make it as easy as possible to test source ranges and warnings, as they're key to the user experience of the analyzer and downstream tools.

Add a simple test class for testing source ranges.

---

CHANGELOG.md
src/html/html-import-scanner.ts
src/html/html-parser.ts
src/html/html-script-scanner.ts
src/html/html-style-scanner.ts
src/parser/document.ts
src/polymer/css-import-scanner.ts
src/test/html/html-import-scanner_test.ts
src/test/html/html-parser_test.ts
src/test/html/html-style-scanner_test.ts
src/test/polymer/css-import-scanner_test.ts
src/test/static/base-href/doc-with-base.html

Document now includes a `baseUrl` property which is properly resolved from an HTML document's `<base href="...">` tag, when present.

Honor thy <base> tag and resolve thy urls according to its href attribute.

---

CHANGELOG.md

Cutting release so bundler can depend on analyzer's new baseUrl-based import url resolution for transitive dependencies.

Modified CHANGELOG to prepare for 2.0.0-alpha.24 release.

---

custom_typings/main.d.ts
custom_typings/performance-now.d.ts
package.json
src/perf/parse-all-benchmark.ts

Landed in https://github.com/braveg1rl/performance-now/pull/8

Use new upstreamed performance-now typings.

---

src/polymer/expression-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/generate_elements_test.ts
src/test/polymer/expression-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts

- Builds on top of #467
I'm not super happy with ScannedDatabindingExpression. There's too many fields that are sometimes present, sometimes absent, etc. Considering breaking it up into a few related types but I don't quite see a super clean breakdown yet.

Parse inline Polymer databinding expressions.

---

CHANGELOG.md
src/polymer/dom-module-scanner.ts
src/polymer/expression-scanner.ts
src/test/polymer/dom-module-scanner_test.ts
src/test/polymer/expression-scanner_test.ts

All hooked up and ready to go.
Builds on #469 
A few design notes:
* We're currently only bothering to parse and track expressions off dom-module templates, though the code knows how to handle stuff like dom-bind as well.
* Uses espree to parse the expressions, but that's actually a very small part of this code. It'd be fairly easy to swap out a different parser. I did discover a couple places where Polymer expressions are invalid javascript: `foo.*` and `arr.0`. Other than that and two (I think legit!) errors, this parses all of PolymerElements without a problem or noticeable performance impact.

Expression parsing all hooked up and usable

---

CHANGELOG.md
package.json

Otherwise you can't npm install this version of analyzer.
Also prepare changelog for stamp of next release.

Add bin dir to files array in package.json

---

src/model/document.ts

`css-import` was omitted from the `FeatureKinds` list for Imports.  Added because bundler needs it cast this way from the Analyzer.

Add css-import to the FeatureKinds for Import

---

CHANGELOG.md
src/test/url-loader/package-url-resolver_test.ts
src/test/utils_test.ts
src/url-loader/fs-url-loader.ts
src/url-loader/package-url-resolver.ts
src/utils.ts

Analyzer believes that `//host/path` is an absolute path that is loadable by FSUrlLoader, for example, instead of it being a protocol-less URL pointing to `/path` on `host`.  Added a `parseUrl` drop-in replacement function for `url.parse` and am using it now in the places it needs to be used, such as `FSUrlLoader` and `PackageUrlResolver`.

Add a `parseUrl` utility function to address shortcomings in Node's `url.parse` function with protocol-less URLs aka `//host/path`.

---

CHANGELOG.md
src/test/analyzer_test.ts
src/test/static/spaces in file.html
src/test/url-loader/package-url-resolver_test.ts
src/url-loader/package-url-resolver.ts

When its a URL, it should be URI-encoded.  Also, `(decode|encode)URIComponent()` is too aggressive to normalize pathname.  Switched to `(decode|encode)URI()`
- Fixes #496

Escape unsafe chars in urls

---

src/test/analyzer_test.ts

This is just the addition of another test to demonstrate that both encoded and unencoded urls can be offered to the `Analyzer.analyze()` method, because of the accommodating behavior of PackageUrlResolver.

Added another test to demonstrate that analyze method accepts unencoded as well as encoded urls.

---

CHANGELOG.md

- Addresses the URL handling issue so that bundler wont get a regression preventing bundling files with unsafe chars in names and this hopefully resolves build's existing issue with same.

Updated CHANGELOG.md in preparation for 2.0.0-alpha.28 release.

---

package.json

`dom5` 2.1.0 introduced a new function `defaultChildNodes` which is used in the `polymer/dom-module-scanner` per #470.
However the dependency was not updated in `package.json`, meaning that an installation of `polymer-analyzer` might fail and resolve the incorrect version of `dom5`.

Update version of dom5 to fix undefined function

---

CHANGELOG.md
src/javascript/ast-value.ts
src/javascript/namespace-scanner.ts
src/polymer/behavior-scanner.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/analyzer_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/js-behaviors.js
src/test/static/namespaces/namespace-unnamed.js
src/test/static/polymer2/test-element-6.js
src/test/static/polymer2/test-element-8.js
src/test/static/polymer2/test-mixin-2.js
src/test/static/polymer2/test-mixin-3.js
src/test/static/polymer2/test-mixin-4.js
src/test/static/polymer2/test-mixin-5.js
src/test/static/polymer2/test-mixin-6.js
src/test/static/polymer2/test-mixin-8.js

- Polymer 2.0 Elements: className inherits from `@memberof` value if one is given
- Polymer 2.0 Mixins: name inherits from `@memberof` value if one is given
- Behaviors: name inherits from `@memberof` value if one is given (If no explicit full name is given to `@polymerBehavior`)
- Polymer 1.0 Elements: No change / no `@memberof` support
- Polymer 1.0 Mixins: No change / no `@memberof` support
---
- Resolves #495
/cc @justinfagnani @usergenic

add support to understand the @memberof jsdoc tag

---

CHANGELOG.md
src/javascript/jsdoc.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/javascript/jsdoc_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts

- Fixes #501 (Fix good descriptions being overwritten in the mixin scanner.)
- Fixes bad formatting with extra newlines in jsdoc descriptions. There still may be some weirdness going on with how this happens, to be investigated later.
- Changelog updated.

fix the mixing description problem, fix bad description formatting

---

package.json

Doesn't run on install, only when actually publishing.

prepublish -> prepublishOnly

---

CHANGELOG.md
src/analyzer.ts
src/core/analysis-context.ts
src/test/analyzer_test.ts

- Addresses #547 supporting line-item property forking by letting `_fork()` take options.

Added options to the `_fork` method and also made `_fork` public and experimental on AnalysisContext.

---

src/javascript/ast-value.ts
src/test/analyzer_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/static/namespaces/namespace-dynamic-unnamed.js

It was treating `foo[bar]` the same as `foo.bar` and `foo['bar']`.

Fix a subtle issue in getIdentifierName

---

src/polymer/dom-module-scanner.ts
src/polymer/expression-scanner.ts
src/test/polymer/expression-scanner_test.ts

For stuff like the observers array, computed properties, etc.
Not hooked up anywhere yet, will do that in a followup PR.

Parse databindings in JS string literals.

---

custom_typings/estraverse.d.ts
custom_typings/main.d.ts
package.json
src/javascript/esutil.ts

This is a known bug in typescript: https://github.com/Microsoft/TypeScript/issues/6496#issuecomment-281852127
This workaround adds minimal estraverse typings for our use case as a local custom typing so that no compiler instance sees both definitions.
I put together a minimal repro here for further investigation and to quickly evaluate fixes: https://github.com/rictic/repro-npm-link-typescript-issue

Fix the typescript part at least of `npm link`

---

.npmignore

This will save >1.5MB for all downstream projects.

Tighten down our .npmignore

---

src/html/html-document.ts
src/parser/document.ts
src/polymer/expression-scanner.ts
src/test/parser/document_test.ts

Builds on top of #569 
This change deletes a bunch of code, but fortunately there's really good tests of the deleted code, so we can be confident that the replacement is equivalent. See the tests for html document and polymer expressions.

Use a fast and simple method to convert between offsets and source ranges

---

CHANGELOG.md
src/model/package.ts
src/test/static/project-with-errors/build/output.html
src/test/static/project/build/output.html

Seems like a reasonable default.
Fixes https://github.com/Polymer/polymer-cli/issues/616

Treat `build` dir as external too.

---

CHANGELOG.md
package.json
src/analysis-format.ts
src/generate-analysis.ts
src/test/static/analysis/behaviors/analysis.json

- Prior PR (merged) had PolymerBehaviors serialized as ElementMixins and put into Analysis.mixins.
- That was iffy, so we decided to move them into Analysis.metadata.polymer.behaviors which feels better.
- Required addition of Analysis.metadata?: any in the analysis-format.
- Still serializing them as ElementMixin.  That's open to negotiation, but I had no opinion due to lack of deep familiarity with Behaviors.

Moved the polymer behaviors from Analysis.mixins => Analysis.metadata.polymer.behaviors

---

CHANGELOG.md
src/warning/warning-printer.ts

This change deals with output of warnings for lines that are indented by tabs.  Previously tabs were counted as a single character causing the squiggle underline to be indented by a single space.  Now the prefix uses tabs to prefix the squiggle where tabs were used on the source line.

Handle tab prefix in Warning Printer getSquiggleUnderline.

---

.vscode/settings.json

Per feedback from @rictic to ensure newlines at end of file, I thought I'd add this to settings.json for vscode.

Added setting to .vscode to ensure newline at EOF on save.

---

CHANGELOG.md

- No README update necessary.
- This release includes BREAKING change for Bundler so we aren't doing a full tools release cascade for this one.

Updated CHANGELOG for release.

---

CHANGELOG.md
src/analyzer.ts
src/core/analysis-context.ts
src/test/analyzer_test.ts

- `Analyzer` and `AnalysisContext` have public `canLoad` methods now.
- `AnalysisContext` uses its own `canLoad` method now.
- Opportunistically added missing comments and type annotations.
- Fixes https://github.com/Polymer/polymer-analyzer/issues/612

Added a canLoad method to Analyzer

---

CHANGELOG.md
src/warning/warning-printer.ts

I've seen this a couple times, working to track it down but it's way easier with the warning code (and we don't want to disrupt users too much in this sort of situation).
I'll be looking into this in more detail.

Recover from undefined source ranges.

---

CHANGELOG.md
src/perf/parse-all-benchmark.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-config.ts
src/polymer/polymer2-element-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-9.js

This PR subsumes https://github.com/Polymer/polymer-analyzer/pull/609 
It should otherwise be a noop change, though I'd expect it to fix some weird bugs. It's a stepping stone to #563 
Conceptually the idea is that in one pass we identify all classes and potential custom elements, and in a separate visitor we collect up all `customElements.define` calls. We then produce ScannedPolymerElements from these two lists using pretty much the same logic as before.

Refactor Polymer 2.0 element scanner into phases

---

src/polymer/polymer2-element-scanner.ts
src/polymer/pseudo-element-scanner.ts
src/test/core/analysis-cache_test.ts
src/test/polymer/polymer2-element-scanner_vanilla-elements_test.ts
src/test/scanning/scan_test.ts

Chai equality typings now verify that the type on the left hand side matches the type on the right hand side. This caught a few places in tests that we were playing fast and loose, as well as one place where we had null where our types said undefined.

Fix compile to work with better chai typings.

---

package.json

It turns out that while `npm` doesn't check node version, yarn does

Fix required node version.

---

src/test/url-loader/multi-url-loader_test.ts
src/url-loader/multi-url-loader.ts

This `MultiUrlLoader` is a very simple implementation.  It depends on `canLoad` to choose the loader to use, in sequence.
My intent with this loader is to support dispatching to multiple loaders to support cases such as the `redirect` option bundler use to use to deal with Chrome's special protocol paths.  To do that will require a different form of the current FSUrlLoader than we have, but because this multi-loader is such a basic compositional tool for loader assembly, I thought I'd add in its own PR.

Add a MultiUrlLoader for loader composition.

---

CHANGELOG.md

* [BREAKING] The `ElementLike` interface in `AnalysisFormat` changed its `demos` property from `string[]` to `Demo[]`, to include more information from `@demo` annotations in Jsdocs.
* [minor breaking change] Simplify rules for infering privacy. Now all features: classes, elements, properties, methods, etc have one set of rules for inferring privacy. Explicit js doc annotations are respected, otherwise `__foo` and `foo_` are private, `_foo` is protected, and `foo` is public.
* Fixed issue where jsdocs syntax in HTML comments was not parsed for polymer elements.

Updated CHANGELOG for 2.0.0-alpha.41 release.

---

src/test/url-loader/prefixed-url-loader_test.ts
src/url-loader/prefixed-url-loader.ts

In combination with the `MultiUrlLoader`, the `PrefixedUrlLoader` provides a mechanism to map multiple url prefixes (containing protocols, domains, paths, whatever), to different delegate loaders.  This provides developers the solve several use cases:
- Route a specific url to a common directory outside the package root.  E.g. I want to point `/bower_components/polymer/` to `~/src/polymer-fork`.
```js
new MultiUrlLoader([
new PrefixedUrlLoader('bower_components/polymer', 
new FSUrlLoader('~/src/polymer-fork')), 
new FSUrlLoader()])
```
- Chrome can create a sequence of mappings for each chrome protocol like: (`bin/polymer-bundler` could easily construct this and implement the old vulcanize `--redirect` option.
```js
new PrefixedUrlLoader('chrome://downloads/',
new …
```

Prefixed url loader 🔥🤘

---

CHANGELOG.md
src/index.ts

- Fixed demo annotation issue, unblocking docs effort for 2.0
- BONUS: This will also provide the PrefixedUrlLoader + MultiUrlLoader combo enabling options for polymer bundler to provide alternative to vulcanize's redirect option.

Updated CHANGELOG for 2.0.0-alpha.42 release.

---

CHANGELOG.md
src/polymer/behavior-scanner.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/js-behaviors.js

We were treating them as properties, but now if they're function typed we call 'em methods.
Fixes #681

Track methods on behaviors properly.

---

CHANGELOG.md
package-lock.json
package.json
src/core/analysis-context.ts
src/test/typescript/typescript-analyzer_test.ts

- Updated `package.json` and `package-lock.json` such that typescript is now a `devDependencies` member.
- Only one non-test source file effected (`analysis-context.ts`), which had an import of the `TypeScriptPreparser`.
- Updated the `TypeScriptParser` test suite by explicitly setting the parsers map for analyzer used in test, since it is not a registered default parser now.

Take TypeScript out of the production dependencies for Analyzer until support fully implemented

---

CHANGELOG.md

- Removed TypeScript from production dependencies until TypeScript analysis is fully supported.

Prepare release of 2.2.1 version of analyzer (now with no typescript)

---

CHANGELOG.md
src/html/html-document.ts
src/model/class.ts
src/model/inline-document.ts
src/polymer/polymer-element.ts
src/test/core/analyzer_test.ts
src/test/static/paper-input.html
src/test/static/polymer2/test-element-15.html

Fixes #689
Improves on #674 as we'll do a better job of not picking up on unrelated comments.
The solution was surprisingly subtle! The core of it is `getPreviousSiblings`.

Fix the "fresh new hell" HTML comment bug.

---

CHANGELOG.md
src/polymer/analyze-properties.ts
src/test/polymer/polymer-element_test.ts
src/test/static/polymer2/test-element-17.js

By accident I discovered that this value was incorrectly `false` if it was explicitly set to `true`. Seemed like a copy-paste error, but there was no existing test for it. Thus I also added an extra test to test for the different property configurations.

Fix value of reflectToAttribute for polymer properties

---

src/javascript/class-scanner.ts
src/test/polymer/polymer-element_test.ts
src/test/static/polymer2/test-element-3.js

While browsing through the http://wpt.fyi source, I found https://github.com/GoogleChrome/wptdashboard/blob/d769c47c245b5e68ba36b925c4950908f0a0d965/components/test-file-results.html#L79 which was showing warnings in my editor. It seems that `window.` parent classes were incorrectly referenced.
I am not 100% convinced this is the correct fix, as it could be that it introduces false positives when defining an object like `Polymer = { Element: ... }`, but that seems a rare edgecase. I also tried to modify https://github.com/Polymer/polymer-analyzer/blob/1d803aceced80c92501fb6144d530139778c66b6/src/javascript/class-scanner.ts#L381 to add it automatically on `window`, but that seemed to break a lot of existing tests.

Resolve window references in extends clause

---

src/javascript/javascript-parser.ts
src/test/javascript/javascript-parser_test.ts

In preparation for supporting explicit module import graph traversal and handling of JS modules vs JS scripts, I updated the `javascript-parser.ts` code and tests to add `JavaScriptScriptParser` and `JavaScriptModuleParser` classes.
We had discussed `parseScript` and `parseModule` methods as part of `JavaScriptParser` except the interface for `Parser` in analyzer is they provide a single `parse()` method and this was the way to continue support for that interface without losing anything.
Also, I preserve the `JavaScriptParser` behavior precisely because the analyzer has a file-extension-to-parser map which would have to be redesigned if a single extension could refer to parsers of different types.  That can be refactored later, but this provides a way to add the desired strictness without …

Parse script v parse module

---

CHANGELOG.md
src/javascript/esutil.ts
src/polymer/js-utils.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/js-behaviors.js

This came up during parsing of
https://github.com/PolymerElements/iron-form-element-behavior/blob/6087b69013619e5b3e023a10824d25cf7530d1fc/iron-form-element-behavior.html#L74-L84 where conditionals are used instead of direct assignments.

Fix parsing of non-primitive Expressions

---

CHANGELOG.md
src/javascript/esutil.ts
src/test/javascript/class-scanner_test.ts
src/test/static/class/class-methods.js

Before this change, rest parameters (e.g. `foo(...args)`) would have the `...` included in their name, and would not include any information from their JSDoc annotation.
Now the parameter name does not include the `...`, and the JSDoc annotations are correctly linked (note that the *type* includes the `...` to make it clear this is a rest parameter). This is how regular functions already work in Analyzer

Handle method rest parameters.

---

CHANGELOG.md
src/javascript/esutil.ts
src/model/method.ts
src/test/javascript/class-scanner_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/class/class-methods.js

Also builds method parameters in a generally more principled way, by unpacking the AST instead of relying on the escodegen library.

Add defaultValue and rest fields to method params.

---

CHANGELOG.md
package-lock.json
package.json

- also removed an unused dependency on jsdoc-to-markdown which I think was previously used to produce docs back in the hydrolysis days. This should clear up github's warning about our deps being vulnerable: https://github.com/Polymer/polymer-analyzer/network/dependencies#487603

Prepare to release v2.7.0

---

src/test/test-utils.ts

A useful, but somewhat viral annotation.

Convert a few more types to ReadonlyArray

---

src/test/javascript/class-scanner_test.ts

tsc was complaining that this particular value in the test file was not a ReadonlyArray after c07b68b8c9f1871c64968f51187a054b1abe1efd

Fix type mismatch arising from c07b68b8c9f1871c64968f51187a054b1abe1efd conversion to ReadonlyArray.

---

CHANGELOG.md
src/javascript/function-scanner.ts
src/test/javascript/function-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-core-feature_test.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/static/namespaces/annotated-functions.js

Part of https://github.com/Polymer/gen-typescript-declarations/issues/23
(Also ran clang-format, so look at the second commit separately.)

 Analyze @global functions, and respect @function name override.

---

CHANGELOG.md

* Added `js-import` feature with `lazy: true` for dynamic imports call expressions of the form `import()`.
* Functions will now be scanned if they have a `@global` annotation. Previously they would only be scanned if they had a `@memberof` annotation. One of these annotations is required because otherwise a lot of functions that aren't really public are included in the analysis (e.g. because they are hidden due to their scoping).
* Function names can now be overridden with e.g. `@function MyNewName`.
- This release will make possible to test bundler PR treating dynamic es module imports as lazy edges.

Updated CHANGELOG for 3.0.0-pre.2 release.

---

CHANGELOG.md
src/model/model.ts

- Since the branded URLs are a part of the external interface they should be exported top-level.
- Also, alphabetically ordered package names in model.ts where they were out-of-order.

Added `url` to the top-level/model exports and sorted import sources.

---

CHANGELOG.md
README.md
src/core/analyzer.ts
src/demo/polymer-lint.ts
src/test/analysis-format/generate-analysis_test.ts
src/test/core/dependency-graph_test.ts
src/test/css/css-custom-property-scanner_test.ts
src/test/html/html-document_test.ts
src/test/html/html-element-reference-scanner_test.ts
src/test/html/html-import-scanner_test.ts
src/test/html/html-script-scanner_test.ts
src/test/html/html-style-scanner_test.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/function-scanner_test.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/css-import-scanner_test.ts
src/test/polymer/dom-module-scanner_test.ts
src/test/polymer/polymer-core-feature_test.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner_vanilla-elements_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/polymer/pseudo-element-scanner_test.ts
src/test/test-utils.ts
src/test/typescript/typescript-import-scanner_test.ts

Two things here:
* Add a method `Analyzer.forDirectory` which encapsulates the process of getting a well configured analyzer rooted at a given directory. This is nice to land here because it's about to change, as the package url resolver is going to want to know about the root dir too.
* Modified way that we write most of our tests to depend less on internals, and to the degree that we do depend on internals, use a single test method to do so.
This is a piece pulled out the url resolution PR.

[Redesigned URLS 1] Add Analyzer.forDirectory; cleanup tests.

---

CHANGELOG.md
src/core/analysis-context.ts
src/core/analyzer.ts
src/html/html-script-tag.ts
src/model/import.ts
src/test/core/analyzer_test.ts
src/test/typescript/typescript-analyzer_test.ts
src/test/typescript/typescript-import-scanner_test.ts
src/test/url-loader/multi-url-resolver_test.ts
src/test/url-loader/package-url-resolver_test.ts
src/test/url-loader/redirect-resolver_test.ts
src/typescript/typescript-analyzer.ts
src/url-loader/multi-url-resolver.ts
src/url-loader/package-url-resolver.ts
src/url-loader/redirect-resolver.ts
src/url-loader/url-resolver.ts

This revealed a number of places where we were not handling unresolvable URLs well. Places where we'd have thrown errors rather than gracefully failing.

[Redesigned URLS 3] Remove UrlResolver#canResolve

---

CHANGELOG.md
src/core/analysis-context.ts
src/html/html-script-tag.ts
src/javascript/javascript-import-scanner.ts
src/test/html/html-script-scanner_test.ts
src/test/static/base-href/imports-js-module-with-base.html

- Fixes https://github.com/Polymer/polymer-analyzer/issues/795 where inline JavaScript module import statements did not honor their containing document's baseUrl.
- Inline documents now inherit baseUrl from their containing documents.
- Thanks @justinfagnani for showing me where scanned inline documents are born.

Inline Documents inherit Container Document base href

---

CHANGELOG.md

* Add Analyzer.forDirectory() for easily getting a well configured analyzer
for a given directory.
* Removed the `UrlResolver#canResolve` method. A UrlResolver should return
`undefined` when `resolve` is called to indicate that it can't resolve a URL.
* Analyzer#urlResolver is a property that exposes the analyzer's url resolver,
for cases where more direct access to url resolution is desired.
* Fix a situation where a warning would be reported as `[Object object]`.
* Fix issue where inline JavaScript module import statements did not honor
their containing document's baseUrl; inline documents now inherit baseUrl
from their containing documents.

Updated CHANGELOG for 3.0.0-pre.4 release.

---

CHANGELOG.md
src/polymer/analyze-properties.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/analysis/behaviors/analysis.json
src/test/static/analysis/mixins-old-jsdoc/analysis.json
src/test/static/analysis/mixins/analysis.json
src/test/static/analysis/simple/analysis.json
src/test/static/analysis/weird-property-names/analysis.json

Polymer property definitions include a `type` field. This is a reference to the constructor that will be used to deserialize attribute values.
In the absence of an explicit `@type` annotation, this deserializer is also used by Analyzer to infer the Closure syntax property type.
Previously, we emitted one of: `string|boolean|number|Object|Array|Date`. Note that in Closure syntax, some of these types are nullable, others aren't (all non-primitive types in Closure are nullable by default), and none can be `undefined`.
Now, we always emit a possibly `null|undefined` type when inferring the property type.
We also now store the original attribute deserializer constructor name in the `attributeType` field.
For context, see this comment on the generated Polymer TypeScript declarations: …

Assume Polymer properties are possibly null|undefined; add attributeType.

---

src/css/css-custom-property-scanner.ts
src/css/css-document.ts
src/test/css/css-custom-property-scanner_test.ts

This aligns us with the vscode css languageserver, so that users don't see duplicate definitions when they find references/jump to definition. Related: https://github.com/Microsoft/vscode/issues/39890

Give ranges for css custom property declarations only on the name.

---

.vscode/tasks.json
gulpfile.js
package.json
src/test/analysis-format/generate-analysis_test.ts
src/test/core/analyzer_test.ts
src/test/core/dependency-graph_test.ts
src/test/css/css-custom-property-scanner_test.ts
src/test/css/css-parser_test.ts
src/test/html/html-document_test.ts
src/test/html/html-parser_test.ts
src/test/html/html-script-scanner_test.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/function-scanner_test.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/javascript/javascript-parser_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-core-feature_test.ts
src/test/polymer/polymer-element-old-jsdoc_test.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner_vanilla-elements_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/test-utils.ts
src/test/url-loader/fetch-url-loader_test.html
src/test/warning/warning-printer_test.ts

We're now mostly limited by the speed at which our tests run.
There's two parts of this change:
* use `tsc-then` to keep the typescript compiler warm
* read our fixtures out of src/, never copy them over into lib/

Speed up `npm run test:watch`

---

CHANGELOG.md
src/core/analysis-context.ts
src/core/utils.ts
src/html/html-document.ts
src/javascript/javascript-parser.ts
src/model/analysis.ts
src/test/core/analyzer_test.ts

Introduce `getDocumentContaining` to find containing inline document for a feature, originally from https://github.com/Polymer/polymer-linter/blob/9d692d3dbc621b9be898006d92f516ffa4a56eaf/src/polymer/call-super-in-callbacks.ts#L125
Also fix several other easy TODO's.
Fixes #557

Resolve several TODO's and implement getDocumentContaining

---

CHANGELOG.md
src/core/utils.ts
src/model/analysis.ts
src/model/warning.ts
src/url-loader/fs-url-loader.ts

This method will be useful in the CLI, where we need to get these paths in order to write out files when fixing lint warnings.
This also fixes a bug whereby we weren't verifying that the loaded file contained within the root dir.

Expose FSUrlLoader#getFilePath

---

src/model/analysis.ts
src/model/document.ts

This is optional and backwards compatible, but it's useful sometimes when we know the type of a Document's parsed document.
See discussion at https://github.com/Polymer/polymer-editor-service/pull/113 which spawned this

Add type parmeter to Document.

---

package-lock.json
package.json
src/index.ts
src/warning/warning-printer.ts

* tsc-then isn't a dev dep
* my refactoring of WarningPrinter left a couple of compile errors

Fix a couple of minor issues.

---

src/polymer/polymer-element.ts
src/test/static/analysis/class/analysis.json

This helps with polymer/polymer#5000.
We were not adding the static methods we detected on a polymer element to the scanned class.

detect static methods in polymer elements

---

CHANGELOG.md
src/core/analysis-context.ts
src/html/html-parser.ts
src/html/html-script-tag.ts
src/model/import.ts
src/test/test-utils.ts
src/test/typescript/typescript-analyzer_test.ts
src/test/url-loader/multi-url-resolver_test.ts
src/test/url-loader/package-url-resolver_test.ts
src/test/url-loader/redirect-resolver_test.ts
src/test/url-loader/url-resolver_test.ts
src/url-loader/multi-url-resolver.ts
src/url-loader/package-url-resolver.ts
src/url-loader/redirect-resolver.ts
src/url-loader/url-resolver.ts

We talked about reversing `UrlResolver#relative()` to make it `(to, from)` but I thought I'd apply the straw-man gambit and take a stab at flipping around `UrlResolver#resolve(baseUrl, url)` instead.
One nice side effect of this is that the type of the unresolvedUrl is known based on whether optional baseUrl is provided, since the typings of the two method forms are:
1. `UrlResolver#resolve(baseUrl: ResolvedUrl, unresolvedUrl: FileRelativeUrl)`
2. `UrlResolver#resolve(unresolvedUrl: PackageRelativeUrl)`
* [BREAKING]: `UrlResolver#resolve()` argument order swapped so that the optional `baseUrl` argument comes first instead of second.  This makes resolve more similar to `url.resolve`.

UrlResolver#resolve(baseUrl, fileRelativeUrl)

---

src/core/analysis-context.ts
src/scanning/scan.ts
src/test/core/analyzer_test.ts

Pass along info on why we failed rather than producing `[Internal Error]`.
This would have helped us diagnose #832 more easily, which I think has been around for a while.
Fixes https://github.com/Polymer/polymer-analyzer/issues/834

Make error handling during parsing or scanning more robust.

---

CHANGELOG.md
src/polymer/docs.ts
src/test/javascript/esutil_test.ts

* Use the annotation description before trying the tag description (Fixes #836)

Detect event descriptions correctly

---

CHANGELOG.md
src/test/url-loader/redirect-resolver_test.ts
src/url-loader/redirect-resolver.ts

- `RedirectResolver` resolves URLs which start with its redirect-to.
The problem is that redirect resolvers produce resolved urls which they later return `undefined` when asked to resolve again.  UrlResolvers should essentially be idempotent, in that once a URL is resolved, it should stay resolved.
This fix prevents a particularly awkward case where a `MultiUrlResolver` includes a `RedirectResolver` which produce a resolved URL which points to files outside the package root, which the subsequently racked `PackageUrlResolver` perceives to be a sibling directory and therefore reroutes to the component directory when the resolved url is subsequently given to `UrlResolver.resolve()`.
While it could be argued that resolved urls should never be asked to be resolved again, at this time we really …

Redirect resolvers should resolve redirects.

---

CHANGELOG.md
src/test/core/analyzer_test.ts
src/test/url-loader/fs-url-loader_test.ts
src/url-loader/fs-url-loader.ts

* `FSUrlLoader#canLoad` *now* reports _false_ for local urls outside the loader's own root; enables fall-thru support needed for racking in `MultiUrlLoader`.

Make FSUrlLoader#canLoad honestly report that it can't load files outside its root

---

CHANGELOG.md

* `FSUrlLoader#canLoad` reports false for local urls outside the loader's
own root; enables fall-thru support needed for use with `MultiUrlLoader`.
* Add `Element#template` for getting the template of an element.
* In MultiUrlLoader, proxy the first implementation of readDirectory, if any.
* Use event annotation descriptions over their tag description.
* `RedirectResolver` resolves URLs which start with its redirect-to.

Updated CHANGELOG for 3.0.0-pre.8 release.

---

CHANGELOG.md
src/test/url-loader/multi-url-resolver_test.ts
src/url-loader/multi-url-resolver.ts

- `MultiUrlResolver` now delegates the `relative()` method to the first
`UrlResolver` in its `_resolvers` array that can `resolve()` the
destination URL.  Makes it possible now to rely on the Analyzer's
resolver to return a valid `PackageRelativeUrl` from a resolved URL.

MultiUrlResolver#relative() fix

---

CHANGELOG.md

* [BREAKING] Document#astNode and ParsedDocument#astNode are now an
`AstNodeWithLanguage`, because we support inline documents in more than just
HTML, as we've added an HTML-in-JS scanner.
* `MultiUrlResolver` now delegates the `relative()` method to the first
`UrlResolver` in its `_resolvers` array that can `resolve()` the
destination URL.  Makes it possible now to rely on the Analyzer's
resolver to return a valid `PackageRelativeUrl` from a resolved URL.

Updated CHANGELOG for 3.0.0-pre.9 release.

---

CHANGELOG.md
src/test/test-utils.ts
src/test/url-loader/multi-url-resolver_test.ts
src/test/url-loader/redirect-resolver_test.ts
src/test/url-loader/url-resolver_test.ts
src/url-loader/multi-url-resolver.ts
src/url-loader/package-url-resolver.ts
src/url-loader/redirect-resolver.ts
src/url-loader/url-resolver.ts

- In order to get a package relative URL back out of a resolver from a ResolveUrl, we essentially call `relative(url)` and it will convert something like `file:///this/package/has/a/file.js` to `has/a/file.js`.
- Now this is true for the `RedirectResolver` which will reverse the effect of a redirect from the provided `url` so as to return a URL relative to the package URL.

RedirectResolver#relative() now correctly represents relative-to-package-root

---

CHANGELOG.md

* [BREAKING] The `UrlResolver#relative()` method now returns a
`PackageRelativeUrl` when called with only one argument, since the only
use of this call form is to reverse a resolved URL back into a simpler
package relative form.

Prepare CHANGELOG for 3.0.0-pre.10 release.

---

CHANGELOG.md
src/javascript/jsdoc.ts
src/test/javascript/jsdoc_test.ts

Fixes #854.
There's some funkiness going on with the pattern here so I just trim it to drop any leftover newlines or CRs.

trim whitespace when parsing jsdoc

---

CHANGELOG.md
package-lock.json
src/polymer/polymer-element-scanner.ts
src/test/polymer/polymer-element-scanner_test.ts

The class, namespace, and behavior scanners already used the common `extractPropertiesFromClassOrObjectBody` function, and now the Polymer element scanner does too. This specifically fixes:
- Use the `@return` annotation to determine the type of a getter.
- The readonly bit was flipped (it was true if a setter existed).
Fixes #876

Use common property extractor on legacy Polymer function calls.

---

CHANGELOG.md
package-lock.json

* Support Windows line endings in JSDoc annotations
* Support scanning of properties in namespaces
* Support scanning of accessors in behaviors
* `Document#getFeatures()` now supports an `excludeBackreferences`
option for use with inline documents to exclude the container/importer
document and its features from the results.
* Support @return annotations on getters/setters on legacy Polymer function
calls, and fix bug where readonly was inverted.
* Add `IndirectUrlResolver`, a URL resolver for very large codebases where
source files map in an arbitrary but predetermined fashion onto URL space.
This resolver is still experimental.
* It is generally true that if something has to be imported from
`polymer-analyzer/lib/...` then it's not yet stable. caveat importer.
* [BREAKING] Removed the …

Updated CHANGELOG and package-lock.json for 3.0.0-pre.11 release.

---

src/javascript/class-scanner.ts
src/javascript/estraverse-shim.ts
src/javascript/estree-visitor.ts
src/javascript/javascript-document.ts
src/javascript/javascript-export-scanner.ts
src/javascript/javascript-import-scanner.ts
src/javascript/jsdoc.ts
src/model/reference.ts
src/polymer/behavior-scanner.ts
src/polymer/behavior.ts
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/core/analyzer_test.ts
src/test/polymer/behavior-scanner_test.ts

* Remove BehaviorAssignment, use ScannedReference instead.
* Include a babel traversal Scope when constructing a ScannedReference
* Basic scanning of exports (not hooked up)
* Also scan re-exports as imports

Mostly no-op change towards scoping

---

CHANGELOG.md
package-lock.json

* Support specifying tag names in jsdoc, e.g. `@customElement fancy-button`
* Add "bare" module specifier support for JavaScript imports and exports. ie,
`import * as jquery from 'jquery'`.

Updated CHANGELOG and package-lock.json for 3.0.0-pre.13 release.

---

CHANGELOG.md
src/core/utils.ts
src/test/url-loader/package-url-resolver_test.ts
src/url-loader/url-resolver.ts

- Fixes https://github.com/Polymer/polymer-analyzer/issues/893 where `UrlResolver#simpleUrlResolve` treated protocol-relative URL like `//something` as a path.

Fixed resolution of protocol-relative URLs.

---

CHANGELOG.md
src/core/utils.ts
src/test/url-loader/package-url-resolver_test.ts
src/url-loader/url-resolver.ts

This reverts commit 8ec3689737362d2e9c6296f277e3901e429b06ce which treated protocol relative URLs like `//foo.com/blah` as valid ResolveUrl.

Revert "Fixed resolution of protocol-relative URLs. (#894)"

---

CHANGELOG.md
src/javascript/javascript-document.ts
src/javascript/javascript-parser.ts
src/polymer/expression-scanner.ts
src/test/javascript/javascript-parser_test.ts
src/test/polymer/expression-scanner_test.ts

We need the `File` for babel traverse to do scope analysis.
This is a breaking change, but there's ~0% chance that anyone is actually broken by this.

Parse JS to a `File` rather than a `Program`

---

CHANGELOG.md
custom_typings/main.d.ts
custom_typings/path-is-inside.d.ts
package-lock.json
package.json
src/core/utils.ts
src/test/core/utils_test.ts
src/test/url-loader/fs-url-loader_test.ts
src/test/url-loader/package-url-resolver_test.ts
src/url-loader/fs-url-loader.ts
src/url-loader/package-url-resolver.ts

If a dependency name began with the name of the package it was being resolved from, we would not resolve the dependency to the components directory, because we were checking for containment naively with string `startsWith`.
Real life example:
- `/repos/iron-icons/a.html` imports `../iron-iconset-svg/b.html`
- We test `"/repos/iron-iconset-svg/b.html".startsWith("/repos/iron-icons")` and did not rewrite the url into the components directory, because it looked like it was already inside the package.

Fix bug in package URL resolution due to startsWith containment check.

---

CHANGELOG.md
src/javascript/esutil.ts
src/polymer/behavior-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/javascript/class-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/class/class-names.js
src/test/static/js-behaviors.js
src/test/static/polymer2/test-mixin-12.js

The first step of resolving imports is to not get tripped up by export syntax :)
Adds a test of class recognition, and fixes up the behavior and mixin scanners to understand named and default export syntax.

Recognize exported behaviors, classes, and mixins.

---

CHANGELOG.md
src/javascript/class-scanner.ts
src/javascript/esutil.ts
src/model/class.ts
src/model/document.ts
src/model/element-base.ts
src/model/queryable.ts
src/polymer/behavior-scanner.ts
src/polymer/polymer-core-feature.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-mixin-scanner.ts
src/polymer/pseudo-element-scanner.ts
src/test/javascript/class-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts

This way we can use babel traverse Scopes to get bindings, use bindings to get NodePaths, use NodePaths to get canonical statements, and then query the Document for the referenced Feature.

 Index referenced features by their statement.

---

CHANGELOG.md
src/javascript/javascript-import-scanner.ts
src/model/import.ts
src/test/javascript/javascript-import-scanner_test.ts

This is a good place to add the original module specifiers, and may be useful hook for caching reference lookups.

Add specialized subclass JS Imports.

---

src/core/analysis-context.ts
src/javascript/esutil.ts
src/javascript/javascript-export-scanner.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/javascript-export-scanner_test.ts
src/test/static/javascript/all-export-types.js

This is useful for matching up imports to exports. No user facing changes yet.

Identify the names of exported bindings.

---

src/javascript/class-scanner.ts
src/javascript/esutil.ts
src/javascript/jsdoc.ts
src/model/reference.ts
src/polymer/behavior-scanner.ts
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts

Not with a Scope.
NodePath is more useful, and it's what we need for scoped reference resolution.

Construct a ScannedReference with a NodePath.

---

CHANGELOG.md
package-lock.json
src/core/utils.ts
src/test/url-loader/indirect-url-resolver_test.ts
src/test/url-loader/package-url-resolver_test.ts
src/test/url-loader/url-resolver_test.ts
src/url-loader/fs-url-resolver.ts
src/url-loader/indirect-url-resolver.ts
src/url-loader/package-url-resolver.ts
src/url-loader/url-resolver.ts

- Fixed issue #893 where FsUrlResolver and IndirectUrlResolver didn't correctly resolve protocol-relative URLs.  These classes now accept a protocol option which defaults to `https` that is prepended when resolving these URLs.
(opportunistically adjusted/normalized some lines in the changelog which had inconsistent indentation)

Fixed resolution of protocol-relative URLs with protocol option.

---

CHANGELOG.md

* Now recognizes classes, behaviors, elements, and mixins that are
declared in an ES6 `export` declaration.
* Document#getFeatures now supports querying by `statement`. Given the
canonical statement (see esutil.getCanonicalStatement), it will lookup
the feature at that statement. This will be used by internal
APIs to do scope-based dereferencing of super classes, behaviors, and mixins.
* Added JavascriptImport#specifier for getting the original import specifier,
before it may have been resolved to a file-relative url by the node module
resolution algorithm.
* Parse concatenated strings in expressions
* Fixed issue where FsUrlResolver and IndirectUrlResolver didn't correctly
resolve protocol-relative URLs.  These classes now accept a protocol option
which defaults to `https` that is …

Prepare CHANGELOG for 3.0.0-pre.15 release.

---

CHANGELOG.md
src/html/html-script-tag.ts
src/model/import.ts
src/test/html/html-script-scanner_test.ts

* Fixed an issue where warnings were generated for imports of resolved URLs
which are not loadable and external to the package.  Now we warn only when
unable to load a document we expect to be loadable.

Stop warning for unloadable documents if we dont expect to be able to load them

---

CHANGELOG.md

* Import URLs which are resolved, but for which the URL loader returns
`canLoad() === false` result in a `not-loadable` Warning instead of
`could-not-load`, which is reserved for other failures, such as parser
errors or load errors.

Prepare CHANGELOG for 3.0.0-pre.16 release.

---

CHANGELOG.md
src/polymer/dom-module-scanner.ts
src/polymer/polymer-element.ts
src/test/polymer/dom-module-scanner_test.ts

This name is required for https://github.com/Polymer/gen-typescript-declarations/pull/100 to properly construct the `HTMLElementTagNameMap[nodeName]` type reference.

Add nodeName to LocalId references

---

CHANGELOG.md
src/javascript/estraverse-shim.ts
src/model/reference.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/static/class/class-names.js
src/test/static/class/reexported-all.js
src/test/static/class/reexported-classes.js
src/test/static/class/super-class-imported.js
src/test/static/class/super-class-scoped.js

This has all of the other PRs merged in. Will rebase to undo the merge commits after those other PRs land, or we can just review everything all at once here.
Scoped reference resolution could be enhanced further. e.g. it wouldn't be hard to resolve through const assignments. I've got that working in one of my prototype branches actually.

Resolve references through imports

---

CHANGELOG.md

* [BREAKING] `FSUrlLoader` is now `FsUrlLoader`.
* Reference resolution now supports javascript scoping rules, and will follow
javascript module imports, including aliased imports, namespace imports, and
re-exports. References to super classes, mixins, and behaviors use this
resolution system.
* Add `nodeName` to `LocalId` references
* Added an `Export` feature, for JS module exports.

Prepare CHANGELOG for 3.0.0-pre.17 release.

---

CHANGELOG.md
src/javascript/resolve-specifier-node.ts
src/test/javascript/resolve-specifier-node_test.ts
src/test/static/javascript/resolve-specifier-node/node_modules/@scope/scoped/package.json
src/test/static/javascript/resolve-specifier-node/node_modules/shallow/package.json

I'm not 100% sure this is right. This does make the tests in https://github.com/Polymer/polyserve/pull/266 pass (after I added another case where I think the golden was wrong). I changed the approach slightly, and tried to think about it more directly in terms of what polyserve is doing:
If you were served from a `/components/` URL (which we can tell because a `componentInfo` was passed in), but your document path is not inside the component dir on _disk_, then this must be the special "own package" case where you are serving some package root as though it were a component sibling. We can then get the right relative path just by imagining that the file on disk actually was located in the components directory, and then computing the relative path as normal.
Part of …

Fix own-package component directory handling in node resolution.
