Polymer/polymer-analyzer

test/test.js

Fix FSResolver tests for new root config usage

Add NoopResolver tests

---

hydrolysis-analyzer.html

<hydrolysis-analyzer>

---

lib/ast-utils/docs.js

fix findlastchildnamed

---

lib/ast-utils/ast-value.js

Fixes https://github.com/PolymerLabs/polylint/issues/63

support binaryexpresson with +

---

package.json

Init will run on compile if necessary.

Autoinit typings

---

src/ast-utils/element-finder.ts
test/js-parser.html
test/static/es6-support-simple.js
test/static/es6-support.js

Fix ES6 classes with ES5 elements, Fix #243

---

src/analyzer.ts
src/loader/xhr-resolver.ts

Send credentials with XHR loader

---

src/analysis.ts
src/analyzer.ts
src/serialized-analysis.ts

* Stubbed out implementation of the `Context` object, which I've named `Analysis` (it's what you get from asking an analyzer to analyze!
* Wrote out and documented interfaces for the metadata format, which I've called `SerializedAnalysis`.
* Wrote out an example for paper-button here: https://gist.github.com/rictic/b6fd4f19b6f265753d5d11cdb8a41940

Initial typing of a serialized analysis

---

custom_typings/espree.d.ts
src/analyzer.ts
src/ast/import-descriptor.ts
src/javascript/javascript-import-scanner.ts
src/javascript/javascript-parser.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/javascript/javascript-parser_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/javascript/module-with-named-import.js
src/test/static/javascript/module.js
src/test/vanilla-custom-elements/element-scanner_test.ts

This doesn't wire the scanner in yet, but just makes it pass a simple test.

Add JavaScriptImportScanner

---

src/test/url-loader/redirect-resolver_test.ts
src/url-loader/redirect-resolver.ts

Add a redirectResolver

---

src/javascript/javascript-parser.ts
src/polymer/docs.ts
src/test/elements-metadata_tests.ts

Split out of the commit in #300 since that's not gonna land today.

Fix warnings found in latest typescript compiler version.

---

src/analyzer.ts
src/ast/ast.ts
src/ast/document-descriptor.ts
src/ast/import-descriptor.ts
src/ast/inline-document-descriptor.ts
src/ast/literal.ts
src/ast/resolvable.ts
src/ast/scanned-feature.ts
src/html/html-style-scanner.ts
src/polymer/css-import-scanner.ts
src/test/analyzer_test.ts
src/test/html/html-import-scanner_test.ts
src/test/polymer/css-import-scanner_test.ts
src/test/scanning/scan_test.ts

Started moving things to better files, a lot more to do still.

Small cleanups

---

custom_typings/shady-css-parser.d.ts

Add stringifier types to shady-css-typings

---

src/analyzer.ts
src/html/html-import-scanner.ts
src/test/html/html-import-scanner_test.ts

Add an option to synthetically describe lazy HTML imports

---

src/analyzer.ts
src/html/html-import-scanner.ts
src/model/import.ts

Note to self: need to make compiler errors travis errors...
/cc @garlicnation though this isn't your fault, super easy to overlook tsc errors currently. yay gulp.

Fix strict null errors from lazy edges

---

src/editor-service/README.md
src/editor-service/polymer-editor-server.ts
src/editor-service/remote-editor-service.ts
src/test/editor-service/editor-server-test.ts

Also handle invalid JSON over stdin with a helpful error message.

Document the editor service

---

src/model/source-range.ts

Resolves #332
/cc @rictic @justinfagnani

document SourceRange & Position indexing

---

CHANGELOG.md
package.json

FYI @justinfagnani @FredKSchott @usergenic

v2.0.0-alpha.16

---

CHANGELOG.md
src/polymer/behavior.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts

Better warnings when resolving behaviors.

---

package.json

update @types/parse5 to fix broken type def

---

.clang-format

***Only merge when there are no outstanding PRs, and remember to run `npm run format` after merging!***
/cc @rictic

Add common clang-format rules

---

README.md

Update example about how to add the packages

---

src/test/analyzer_test.ts
src/test/scanning/scan_test.ts

Fix two type warnings that come up in typescript 2.1.1

---

CHANGELOG.md
src/generate-elements.ts
src/model/element.ts
src/polymer/dom-module-scanner.ts
src/polymer/polymer-element.ts
src/test/static/analysis/dom-module/documented.html
src/test/static/analysis/dom-module/elements.json

This PR is now finished and fixes #391 
Please see the corresponding PR at https://github.com/Polymer/polymer-editor-service/pull/34 which uses this feature.

Add slots to PolymerElement

---

CHANGELOG.md
package.json

v2.0.0-alpha.18

---

CHANGELOG.md
src/polymer/analyze-properties.ts
src/test/polymer/polymer-element-scanner_test.ts

Small fix to correctly parse shorthand property definitions.
Fixes #357

Correctly parse shorthand property definition

---

package.json
src/perf/parse-all-benchmark.ts

Track memory usage and leaking in the benchmark.

---

src/test/typescript/typescript-preparser_test.ts
src/typescript/typescript-preparser.ts

Also track inline information on typescript documents.
- Internal change, no CHANGELOG modification.

Emit parse errors from the typescript parser.

---

custom_typings/memory-streams.d.ts
custom_typings/performance-now.d.ts
custom_typings/shady-css-parser.d.ts

Annotate upstreamed typings with when we can delete them

---

CHANGELOG.md
src/core/analysis-context.ts
src/editor-service/local-editor-service.ts
src/model/document.ts
src/model/model.ts
src/model/package.ts
src/model/queryable.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts

Allow filtering out features from code external to the current package.

---

CHANGELOG.md

Prepare for release of alpha.23

---

CHANGELOG.md
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-element-scanner.ts
src/test/analyzer_test.ts
src/test/static/html-missing-behaviors.html

More consistent behavior reference determination.

---

src/typescript/typescript-analyzer.ts

Makes progress on, but doesn't solve #458

Fix minor bug in module resolution.

---

src/javascript/javascript-parser.ts
src/polymer/expression-scanner.ts
src/test/polymer/expression-scanner_test.ts

Needed for the linter. For example: https://github.com/Polymer/polymer-linter/issues/29 https://github.com/Polymer/polymer-linter/issues/25 https://github.com/Polymer/polymer-linter/issues/9 and https://github.com/Polymer/polymer-linter/issues/8 will all depend on this work or something much like it.

First, basic pass at scanning databinding expressions.

---

CHANGELOG.md
src/javascript/jsdoc.ts
src/model/attribute.ts
src/model/element-base.ts
src/model/element-mixin.ts
src/model/element.ts
src/model/model.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-config.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/polymer2/test-mixin-1.js
src/test/static/polymer2/test-mixin-2.js
src/test/static/polymer2/test-mixin-3.js
src/test/static/polymer2/test-mixin-4.js
src/test/static/polymer2/test-mixin-5.js
src/test/static/polymer2/test-mixin-6.js

Add Polymer2MixinScanner

---

bin/analyze.js
package.json
src/core/analysis-context.ts
src/elements-format.ts
src/generate-elements.ts
src/javascript/jsdoc.ts
src/model/document.ts
src/model/element-base.ts
src/model/element.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-config.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/polymer2/test-mixin-7.js

I accidentally merged the last PR into the mixins branch. This has already been reviewed.

Find mixins assigned to namespaces

---

src/polymer/expression-scanner.ts
src/test/polymer/expression-scanner_test.ts

Extract property names, validate expressions.

---

CHANGELOG.md

Prepare for release of alpha 25

---

src/editor-service/local-editor-service.ts
src/model/element.ts
src/model/feature.ts
src/model/model.ts
src/model/reference.ts
src/polymer/behavior.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-element-scanner.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-3.js
src/test/vanilla-custom-elements/element-scanner_test.ts
src/vanilla-custom-elements/element-scanner.ts

Add basic inheritance support in PolymerElement

---

src/polymer/polymer-element.ts

I hit an NPE when analyzing paper-button, but couldn't easily distill a test that broke this. Need to get a fix in now though.

Initialize array members of PolymerElement

---

CHANGELOG.md

Updated CHANGELOG for 2.0.0-alpha.27 release.

---

src/generate-elements.ts
src/model/element.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-element-scanner.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-6.js
src/test/static/polymer2/test-element-7.js

@mixes support

---

CHANGELOG.md
src/polymer/polymer2-config.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/polymer2/test-element-1.js
src/test/static/polymer2/test-element-3.js
src/test/static/polymer2/test-element-5.js
src/test/static/polymer2/test-element-7.js
src/test/static/polymer2/test-mixin-1.js
src/test/static/polymer2/test-mixin-2.js
src/test/static/polymer2/test-mixin-3.js
src/test/static/polymer2/test-mixin-4.js
src/test/static/polymer2/test-mixin-5.js
src/test/static/polymer2/test-mixin-7.js

Support new properties/observers getters in Polymer 2.0 elements

---

src/javascript/namespace-scanner.ts
src/javascript/namespace.ts
src/model/element-base.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/namespaces/namespace-unnamed.js
src/test/static/polymer2/test-element-1.js
src/test/static/polymer2/test-mixin-1.js
src/test/static/polymer2/test-mixin-2.js

Add `@summary` support

---

src/elements-format.ts
src/generate-elements.ts
src/polymer/polymer-element.ts
src/test/elements-metadata_tests.ts
src/test/generate_elements_test.ts
src/test/static/analysis/behaviors/elements.json
src/test/static/analysis/bower_packages/elements.json
src/test/static/analysis/dom-module/elements.json
src/test/static/analysis/nested-packages/elements.json
src/test/static/analysis/no-package/elements.json
src/test/static/analysis/separate-js/elements.json
src/test/static/analysis/simple/elements.json
src/test/static/analysis/weird-property-names/elements.json

Add summary and classname to element metadata

---

CHANGELOG.md
src/analyzer.ts
src/test/analyzer_test.ts

- `Analyzer#_fork()` lets you do wonderful divergent parallel things now.

Added an (experimental) _fork method to Analyzer.

---

src/analyzer.ts

Fix compilation error

---

src/polymer/polymer2-element-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-7.js
src/test/static/polymer2/test-element-9.js

Support elements in variable declarations without class expressions.

---

src/elements-format.ts
src/generate-elements.ts

Add mixins to metadata output

---

gulpfile.js
package.json

Don’t fail silently on compile errors

---

CHANGELOG.md
src/elements-format.ts
src/generate-elements.ts
src/javascript/jsdoc.ts
src/model/element-base.ts
src/polymer/js-utils.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/analysis/behaviors/elements.json
src/test/static/analysis/dom-module/elements.json
src/test/static/analysis/no-package/elements.json
src/test/static/analysis/separate-js/elements.json
src/test/static/analysis/simple/elements.json
src/test/static/analysis/simple/simple-element.html
src/test/static/analysis/weird-property-names/elements.json
src/test/static/polymer2/test-element-10.js
src/test/static/polymer2/test-mixin-9.js

This builds on the `methods` detection work to expose the new methods in the analysis results.
/cc @justinfagnani @rictic @usergenic

Use new method analysis in the results elements data format

---

CHANGELOG.md
src/elements-format.ts
src/generate-elements.ts
src/model/document.ts
src/test/static/analysis/namespaces/elements.json
src/test/static/analysis/namespaces/namespaces.html

add functions to element.json metadata format

---

CHANGELOG.md
src/core/analysis-context.ts
src/elements-format.ts
src/generate-elements.ts
src/javascript/esutil.ts
src/javascript/function-scanner.ts
src/javascript/function.ts
src/model/document.ts
src/model/property.ts
src/polymer/polymer-element-scanner.ts
src/test/javascript/function-scanner_test.ts
src/test/static/analysis/namespaces/elements.json
src/test/static/analysis/namespaces/namespaces.html
src/test/static/namespaces/memberof-functions.js

Functions tagged with `@memberof` are now returned by the new function scanner. Returning these functions via analysis is still TODO.

add namespace function scanner

---

CHANGELOG.md
package.json
src/elements-format.ts
src/generate-elements.ts
src/javascript/jsdoc.ts
src/model/feature.ts
src/model/property.ts
src/polymer/docs.ts
src/polymer/js-utils.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/test/editor-service/editor-service_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/analysis/behaviors/elementdir/element.html
src/test/static/analysis/behaviors/elements.json
src/test/static/analysis/simple/elements.json
src/test/static/analysis/simple/simple-element.html
src/test/static/analysis/weird-property-names/elements.json

Track privacy better on properties and methods.

---

CHANGELOG.md
src/elements-format.ts
src/generate-elements.ts
src/polymer/polymer-element.ts
src/test/polymer/polymer-element_test.ts
src/test/static/analysis/behaviors/elements.json

Add inheritedFrom to metadata output

---

CHANGELOG.md
src/javascript/function-scanner.ts
src/javascript/function.ts
src/polymer/js-utils.ts
src/test/javascript/function-scanner_test.ts
src/test/static/namespaces/memberof-functions.js

Track privacy for functions on namespaces.

---

CHANGELOG.md
src/elements-format.ts
src/generate-elements.ts
src/javascript/function-scanner.ts
src/model/element-mixin.ts
src/polymer/js-utils.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/static/analysis/mixins/elements.json
src/test/static/analysis/mixins/mixins.js

Set privacy on mixins.

---

src/analysis-format.ts
src/generate-analysis.ts
src/test/static/analysis/namespaces/analysis.json

Emit privacy on functions

---

src/generate-analysis.ts
src/test/generate_analysis_test.ts

generateAnalysisMetadata -> generateAnalysisMetadata

---

CHANGELOG.md
package.json
src/generate-analysis.ts
src/index.ts
src/test/generate_analysis_test.ts

Add a new main library that exports a public API for the analyzer.

---

CHANGELOG.md
src/generate-analysis.ts
src/javascript/jsdoc.ts
src/model/element-base.ts
src/model/element.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/static/analysis/mixins/analysis.json
src/test/static/analysis/mixins/mixins.js

Emit mixins on mixins in Analysis.

---

CHANGELOG.md

Prepare for alpha 29.

---

CHANGELOG.md
package.json

Prepare for bugfix release alpha.30

---

src/polymer/behavior-scanner.ts
src/polymer/docs.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-element-scanner.ts
src/polymer/pseudo-element-scanner.ts

Add AST nodes to scanned elements and things

---

README.md
src/editor-service/ast-from-source-position.ts
src/editor-service/editor-service.ts
src/editor-service/local-editor-service.ts
src/editor-service/remote-editor-protocol.ts
src/editor-service/remote-editor-service.ts
src/index.ts
src/model/source-range.ts
src/test/editor-service/ast-from-source-position_test.ts
src/test/model/inline-document-descriptor_test.ts

We had a few pieces of the public API missing from index.ts

---

src/javascript/jsdoc.ts
src/polymer/js-utils.ts
src/test/javascript/jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/analysis/simple/analysis.json
src/test/static/polymer2/test-element-1.js
src/test/static/polymer2/test-element-10.js

Produce clean method descriptions

---

src/polymer/analyze-properties.ts
src/polymer/js-utils.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-1.js

@type annotations are canonical for properties.

---

CHANGELOG.md

Prep 2.0.0-alpha.31

---

CHANGELOG.md
src/polymer/polymer2-element-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-11.js

Fixes https://github.com/Polymer/polymer-analyzer/issues/537

Recognize elements registered with MyElem.is

---

CHANGELOG.md
package.json
src/index.ts

Prepare to release alpha.32

---

CHANGELOG.md
src/polymer/polymer-element-mixin.ts
src/polymer/polymer2-mixin-scanner.ts

Add astNodes to mixins.

---

CHANGELOG.md

Prepare to release alpha.33

---

CHANGELOG.md
src/model/document.ts
src/test/analyzer_test.ts
src/test/static/project-with-errors/bower_components/external-with-warnings.html
src/test/static/project-with-errors/index.html

Fix filtering out external features.

---

CHANGELOG.md

Prepare to release alpha.34

---

CHANGELOG.md
src/generate-analysis.ts
src/javascript/namespace-scanner.ts
src/test/editor-service/editor-service_test.ts
src/test/generate_analysis_test.ts
src/test/static/analysis/behaviors/analysis.json
src/test/static/analysis/behaviors/behavior.html
src/test/static/analysis/behaviors/subdir/subbehavior.html

- I put your `PolymerBehaviors` in your `generateAnalysis()['mixins']`
- You can identify them by their `metadata.isPolymerBehavior=true`
Also,
So PTAL!

Analysis.mixins now includes PolymerBehavior serializations

---

src/polymer/dom-module-scanner.ts
src/polymer/expression-scanner.ts
src/test/polymer/dom-module-scanner_test.ts

Fix some typos that I noticed during code walkthrough with aomarks.

---

CHANGELOG.md
src/analysis-format.ts
src/model/method.ts
src/polymer/js-utils.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/analysis/simple/analysis.json
src/test/static/polymer2/test-element-10.js

Extract method params and return types from jsdoc

---

.vscode/settings.json
CHANGELOG.md
src/core/analysis-cache.ts
src/core/dependency-graph.ts
src/html/html-script-scanner.ts
src/html/html-script-tag.ts
src/javascript/javascript-import-scanner.ts
src/polymer/css-import-scanner.ts
src/test/analyzer_test.ts
src/test/core/dependency-graph_test.ts
src/typescript/typescript-import-scanner.ts

Fix dependants in DependencyRecord

---

CHANGELOG.md

Prepare to release alpha.35

---

CHANGELOG.md
src/analyzer.ts
src/core/analysis-cache.ts
src/core/analysis-context.ts
src/editor-service/editor-service.ts
src/editor-service/local-editor-service.ts
src/index.ts
src/perf/parse-all-benchmark.ts
src/test/analyzer_test.ts
src/test/editor-service/editor-service_test.ts
src/test/test-utils.ts
src/test/typescript/typescript-analyzer_test.ts
src/url-loader/in-memory-overlay-loader.ts
src/url-loader/overlay-loader.ts

Remove second argument to analyze(), add filesChanged and InMemoryOverlayLoader

---

.vscode/tasks.json

Looks like a pure shuffling of names? Nothing seems to be changed.

Use new format for .vscode/tasks.json

---

CHANGELOG.md
src/polymer/polymer-element-scanner.ts
src/test/polymer/polymer-element-scanner_test.ts

Fixes https://github.com/Polymer/polymer-analyzer/issues/598

Extract className from Polymer 1 element assignment

---

CHANGELOG.md
src/polymer/expression-scanner.ts
src/test/polymer/expression-scanner_test.ts

Fixes https://github.com/Polymer/polymer-linter/issues/66

Negative numbers are allowed in databindings.

---

.travis.yml
CHANGELOG.md
package.json
src/core/analysis-context.ts
src/editor-service/local-editor-service.ts
src/generate-analysis.ts
src/html/html-script-tag.ts
src/javascript/function.ts
src/javascript/namespace.ts
src/model/analysis.ts
src/model/document.ts
src/model/element-base.ts
src/model/element-mixin.ts
src/model/element-reference.ts
src/model/element.ts
src/model/feature.ts
src/model/import.ts
src/model/inline-document.ts
src/model/model.ts
src/model/queryable.ts
src/model/reference.ts
src/polymer/behavior.ts
src/polymer/dom-module-scanner.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/analyzer_test.ts
src/test/polymer/polymer-element_test.ts

Expose only a single feature query method.

---

CHANGELOG.md

Encompasses what should be the last batch of major breaking changes before v2.0.0

Prepare to release alpha.37

---

src/analyzer.ts

This also will give better IDE experience when constructing a new Analyzer from typescript, as we accept only one type of thing into the Analyzer constructor.

Support synchronously forking Analyzer

---

CHANGELOG.md

Prepare for alpha.38

---

src/core/analysis-context.ts
src/test/url-loader/package-url-resolver_test.ts
src/url-loader/package-url-resolver.ts

Works around https://github.com/Polymer/polymer-analyzer/issues/623 and also fixes an issue with PackageUrlResolver

Fix a couple issues that came up in the linter's integration test

---

CHANGELOG.md
src/analysis-format.ts
src/generate-analysis.ts
src/test/analysis-metadata_tests.ts
src/test/static/analysis/demo/analysis.json
src/test/static/analysis/demo/demo-annotation-in-html-comment.html

- `AnalsysiFormat` now has a `Demo` interface for including description and url to demo.

Added Demo type to AnalysisFormat so demos can have descriptions.

---

CHANGELOG.md
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/editor-service/editor-service_test.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/analysis/behaviors/analysis.json
src/test/static/analysis/mixins/analysis.json
src/test/static/polymer2/test-element-7.js
src/test/static/polymer2/test-mixin-10.js

Fixes https://github.com/Polymer/polymer-analyzer/issues/564
Also removed some use of `Object.assign` in constructors

Mix mixins into mixins.

---

bower.json
package.json
src/analyzer.ts
src/ast-utils/element-finder.ts

Testing this out for a hydrolysis 1.25.0 release

Mute errors in parsing class definitions

---

src/demo/polymer-lint.ts
src/editor-service/ast-from-source-position.ts
src/html/html-document.ts
src/html/html-element-reference-scanner.ts
src/javascript/estree-visitor.ts
src/javascript/esutil.ts
src/javascript/javascript-document.ts
src/javascript/jsdoc.ts
src/model/document.ts
src/polymer/analyze-properties.ts
src/polymer/behavior-scanner.ts
src/polymer/js-utils.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/javascript/class-scanner_test.ts
src/test/polymer/expression-scanner_test.ts
src/test/utils_test.ts
src/typescript/typescript-preparser.ts
tsconfig.json

This appears to have fixed several actual bugs.

Enable stricter checks for indexing expressions

---

CHANGELOG.md

Prepare to release alpha.39

---

CHANGELOG.md

Prepare to release alpha.40

---

CHANGELOG.md
src/javascript/class-scanner.ts
src/javascript/function-scanner.ts
src/model/class.ts
src/polymer/behavior-scanner.ts
src/polymer/js-utils.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element-scanner.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-mixin-scanner.ts
src/polymer/pseudo-element-scanner.ts
src/test/static/analysis/mixins-old-jsdoc/analysis.json
src/test/static/analysis/mixins/analysis.json
src/test/static/analysis/simple/analysis.json

Simple privacy inference

---

CHANGELOG.md
README.md

Prepare to release Analyzer 2.0.0

---

CHANGELOG.md
src/model/class.ts
src/polymer/analyze-properties.ts
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-core-feature-scanner.ts
src/polymer/polymer-element.ts
src/test/core/analyzer_test.ts

Change many errors to warnings

---

README.md

Update README with the stable API

---

CHANGELOG.md

prepare to release 2.0.2

---

CHANGELOG.md
src/model/warning.ts
src/test/core/analyzer_test.ts

toJson is spelled toJSON

---

CHANGELOG.md

Prepare to release 2.1.0

---

CHANGELOG.md
custom_typings/estree.d.ts
custom_typings/main.d.ts
src/javascript/esutil.ts
src/test/javascript/class-scanner_test.ts
src/test/static/class/class-names.js

Fixes one of the issues in https://github.com/Polymer/polymer-analyzer/issues/691

Don't associate comments with nodes unless they are touching.

---

CHANGELOG.md

Prepare 2.2.0 release.

---

package-lock.json
package.json
src/core/analysis-cache.ts
src/core/analysis-context.ts
src/core/async-work-cache.ts
src/javascript/esutil.ts
src/javascript/javascript-scanner.ts
src/model/class.ts
src/model/document.ts
src/model/element-base.ts
src/model/warning.ts
src/parser/document.ts
src/polymer/expression-scanner.ts
src/polymer/js-utils.ts
src/test/core/analyzer_test.ts
src/test/core/dependency-graph_test.ts
src/test/core/utils_test.ts
src/test/scanning/scan_test.ts
src/test/test-utils.ts
src/test/typescript/typescript-analyzer_test.ts
src/typescript/typescript-preparser.ts
src/warning/code-printer.ts

Updates for typescript 2.4

---

CHANGELOG.md
package.json
src/javascript/class-scanner.ts
src/javascript/jsdoc.ts
src/polymer/polymer-element.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/polymer2/test-element-16.js
src/test/static/polymer2/test-mixin-11.js
test/mocha.opts

This is a long awaited feature. @azakus is the latest to be pushing for it.
Fixes #706

Scan fields from ES constructor declarations

---

CHANGELOG.md

Prepare to release v2.2.2

---

CHANGELOG.md
src/core/analysis-context.ts
src/css/css-custom-property-scanner.ts
src/css/css-document.ts
src/css/css-scanner.ts
src/html/html-style-scanner.ts
src/test/css/css-custom-property-scanner_test.ts
src/test/static/some-styles.html

Scan for css custom property uses and assignments

---

CHANGELOG.md
package-lock.json

* Scan for CSS custom variable uses and assignments.
* Fix value of reflectToAttribute for polymer properties.
* Remove scriptElement from PolymerElement.
* `html-style` features are now scanned for inside templates.

Updated CHANGELOG for 2.3.0 release.

---

CHANGELOG.md
src/core/analysis-context.ts
src/model/inline-document.ts
src/test/html/html-script-scanner_test.ts
src/test/static/javascript/module-with-export.js
src/test/static/javascript/submodule.js
src/test/static/js-modules.html

- Scan for module imports in inline and external JavaScript, analyzing the entire import graph.

JavaScript module import scanner

---

CHANGELOG.md
package-lock.json
src/model/element-base.ts
src/polymer/dom-module-scanner.ts

This is useful for the linter.

Add an `astNode` property to Slot.

---

CHANGELOG.md

Prepare to release v2.4.0

---

package-lock.json
package.json
src/model/immutable.ts
src/test/warning/warning-printer_test.ts
src/typescript/typescript-analyzer.ts

Update to typescript 2.6

---

.travis.yml
CHANGELOG.md

Prepare to release 2.4.1

---

CHANGELOG.md

Prepare to release 2.5.0

---

CHANGELOG.md

Prepare 2.6.0 release.

---

CHANGELOG.md
src/analysis-format/generate-analysis.ts

Emit more accurate super classes for Elements when generating analysis JSON

---

CHANGELOG.md
src/model/warning.ts
src/test/warning/warning-printer_test.ts

Fixes https://github.com/Polymer/polymer-linter/issues/115

One indexed

---

src/core/analysis-cache.ts

Note to future self: the bug you're looking for probably isn't in the analysis cache. It's probably much simpler and dumber than that.

Improve analysis-cache.toString()

---

package-lock.json
package.json
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts

Update doctrine to 2.0.2 and fix the two failing tests where whitespace different in a parsed value.
This is a cherry-pick of @rictic's a7e35601b94d4cc59dc4b4d002a3c78458996e86

Update tests for the latest version of doctrine.

---

gulpfile.js
package-lock.json
package.json
src/warning/warning-filter.ts

Also add support for filtering by file globs.
This will make it much easier to have unified behavior across the IDE and CLI for configuring which warnings to ignore.

Construct WarningFilter from ProjectConfig

---

CHANGELOG.md
package-lock.json
src/javascript/function-scanner.ts
src/javascript/function.ts
src/test/javascript/function-scanner_test.ts
src/test/static/namespaces/templated-functions.js

Part of https://github.com/Polymer/gen-typescript-declarations/issues/23

Add templateTypes to functions, extracted from @template annotations.

---

CHANGELOG.md

Prepare 3.0.0-pre.3 release.

---

CHANGELOG.md

Prepare 3.0.0-pre.5 release.

---

CHANGELOG.md
src/demo/polymer-lint.ts
src/model/analysis.ts
src/model/warning.ts
src/test/core/analyzer_test.ts
src/test/html/html-script-scanner_test.ts
src/test/model/warning_test.ts
src/test/polymer/polymer-element-old-jsdoc_test.ts
src/test/polymer/polymer-element_test.ts
src/test/test-utils.ts

Analysis#getDocument returns a Result.

---

.vscode/launch.json
appveyor.yml
gulpfile.js
package.json
src/test/test-utils.ts
src/test/url-loader/package-url-resolver_test.ts
src/test/url-loader/url-resolver_test.ts
src/url-loader/package-url-resolver.ts
src/url-loader/url-resolver.ts

[Redesigned URLS 6] Get all tests passing on windows

---

.vscode/launch.json
CHANGELOG.md
appveyor.yml
gulpfile.js
package-lock.json
package.json
src/core/analyzer.ts
src/model/analysis.ts
src/test/core/analyzer_test.ts
src/test/html/html-document_test.ts
src/test/html/html-script-scanner_test.ts
src/test/polymer/polymer-element-old-jsdoc_test.ts
src/test/test-utils.ts
src/test/url-loader/fs-url-loader_test.ts
src/test/url-loader/package-url-resolver_test.ts
src/test/url-loader/url-resolver_test.ts
src/url-loader/fs-url-loader.ts
src/url-loader/package-url-resolver.ts
src/url-loader/url-resolver.ts

Fixes https://github.com/Polymer/polymer-analyzer/issues/765

[Redesigned URLS 5] Resolve to absolute urls

---

src/core/analysis-context.ts
src/core/analyzer.ts
src/model/analysis.ts
src/model/url.ts
src/test/test-utils.ts
src/typescript/typescript-analyzer.ts
src/url-loader/multi-url-resolver.ts
src/url-loader/package-url-resolver.ts
src/url-loader/redirect-resolver.ts
src/url-loader/url-resolver.ts

Refine the type of UrlResolver#resolve

---

CHANGELOG.md
src/test/url-loader/url-resolver_test.ts

Prepare to release v3.0.0-pre.6

---

src/model/warning.ts

I missed this file when I converted a bunch of our url `string` types to `ResolvedUrl` a little while back. These do need to be resolved urls though, and this is catching some errors in the linter and ide.

Refine the types of applyEdits.

---

CHANGELOG.md
src/model/warning.ts
src/warning/warning-printer.ts

Get relative urls when reporting warnings.

---

package-lock.json
package.json
src/javascript/class-scanner.ts
src/polymer/polymer2-mixin-scanner.ts
src/test/javascript/class-scanner_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/static/class/class-properties.js

This is an attempt at adding the ability to detect getters/setters in the class scanner.
There's a bit of duplication as you can see, so feel free to suggest some refactoring.
Also, what should we do with statics? they are ignored right now.
cc @rictic 
Fixes #645

detect getters/setters as properties

---

src/javascript/esutil.ts
src/polymer/js-utils.ts

Cleans up some common code and an awkward API I noticed in https://github.com/Polymer/polymer-analyzer/pull/821

Renamed closureType to getClosureType, return a Result.

---

src/test/typescript/typescript-preparser_test.ts

Fix flaky typescript tests with longer timeout.

---

src/analysis-format/generate-analysis.ts
src/url-loader/url-resolver.ts

A couple minor changes for browserify compatibility.

---

CHANGELOG.md

Prepare 3.0.0-pre7 release.

---

CHANGELOG.md
src/url-loader/multi-url-loader.ts

Support MultiUrlLoader#readDirectory

---

CHANGELOG.md
src/core/analysis-context.ts
src/html/html-document.ts
src/html/html-script-scanner.ts
src/html/html-style-scanner.ts
src/javascript/estree-visitor.ts
src/javascript/html-template-literal-scanner.ts
src/model/document.ts
src/model/inline-document.ts
src/parser/document.ts
src/test/core/analyzer_test.ts
src/test/javascript/html-template-literal-scanner_test.ts
src/test/test-utils.ts

Part of https://github.com/Polymer/polymer-analyzer/issues/748

 Add basic support for inline HTML in JS

---

design/comment-scanning.md

- Originally brought up in: #614
- `polymer-lint` counterpart: https://github.com/Polymer/polymer-linter/issues/58
- I recommend viewing the rendered file & leaving comments in the diff

Comment Directives & Comment Annotations

---

CHANGELOG.md
package-lock.json
src/polymer/behavior-scanner.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/js-behaviors.js

This is just a rebased form of @43081j 's PR: https://github.com/Polymer/polymer-analyzer/pull/869
Merging through the github UI because I like the way it includes PR metadata onto commits.

rebased PR #869

---

src/javascript/class-scanner.ts
src/javascript/esutil.ts
src/javascript/function-scanner.ts
src/javascript/namespace-scanner.ts
src/polymer/analyze-properties.ts
src/polymer/behavior-scanner.ts
src/polymer/docs.ts
src/polymer/js-utils.ts
src/polymer/polymer-core-feature-scanner.ts
src/polymer/polymer-element-scanner.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/esutil_test.ts
src/test/javascript/jsdoc_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/polymer/pseudo-element-scanner_test.ts

`objectKeyToString` looks like it was originally intended for getting propery names, but then a bunch of other code started using it in ways that they probably shouldn't, and it got extended to handle namespaced identifiers. So we ended up conflating getting identifier names with getting property keys, leading to all sorts of strangeness.
This PR switches the cases where we want an identifier name to call `getIdentifierName`, and redesigns `objectKeyToString` as `getPropertyName`. `getPropertyName` takes a more specific type, and handles computed values correctly.
One motivating example of where we get things wrong today: https://polymer.github.io/analyzer-playground/?input=%3Cbase+href%3D%22https%3A%2F%2Fpolygit.org%2Fpolymer%2B%3Amaster%2Fwebcomponents%2B%3Amaster%2Fshadycss%2Bwebcompone …

Be more principled in computing names.

---

CHANGELOG.md

Prepare 3.0.0-pre.12 release.

---

src/url-loader/fs-url-loader.ts

- Fixes https://github.com/Polymer/polymer-analyzer/issues/878

Refactored the code inside FSUrlLoader to get canLoad to agree with getFilepath

---

src/javascript/class-scanner.ts
src/javascript/function-scanner.ts
src/javascript/jsdoc.ts
src/model/class.ts
src/model/element-base.ts
src/model/element.ts
src/model/reference.ts
src/polymer/behavior-scanner.ts
src/polymer/declaration-property-handlers.ts
src/polymer/polymer-element-mixin.ts
src/polymer/polymer-element.ts
src/test/core/analyzer_test.ts
src/test/test-utils.ts

Now using the same logic for resolving super classes, mixins, and behaviors.
Also parameterized the ScannedReference and Reference types for clarity.

Use a unified reference resolution system.

---

CHANGELOG.md

Prepare 3.0.0-pre.14 release.

---

src/javascript/esutil.ts
src/javascript/javascript-export-scanner.ts
src/javascript/javascript-import-scanner.ts
src/test/javascript/javascript-export-scanner_test.ts
src/test/static/javascript/all-export-types.js
src/test/static/javascript/re-export-all.js

Calculate identifiers for re-exports correctly.

---

CHANGELOG.md
src/javascript/ast-value.ts
src/polymer/expression-scanner.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/static/polymer2/test-element-12.js
src/test/static/polymer2/test-element-20.js

This fixes #656.
Is this approach fine?

parse binary expressions of string literals

---

CHANGELOG.md
README.md
src/core/analyzer.ts
src/demo/polymer-lint.ts
src/test/analysis-format/generate-analysis_test.ts
src/test/core/analyzer_test.ts
src/test/core/dependency-graph_test.ts
src/test/css/css-custom-property-scanner_test.ts
src/test/html/html-document_test.ts
src/test/html/html-parser_test.ts
src/test/html/html-script-scanner_test.ts
src/test/javascript/class-scanner_test.ts
src/test/javascript/function-scanner_test.ts
src/test/javascript/javascript-export-scanner_test.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/javascript/namespace-scanner_test.ts
src/test/polymer/behavior-scanner_test.ts
src/test/polymer/polymer-core-feature_test.ts
src/test/polymer/polymer-element_test.ts
src/test/polymer/polymer2-element-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-element-scanner_test.ts
src/test/polymer/polymer2-element-scanner_vanilla-elements_test.ts
src/test/polymer/polymer2-mixin-scanner-old-jsdoc_test.ts
src/test/polymer/polymer2-mixin-scanner_test.ts
src/test/test-utils.ts

Remove Analyzer.createFromDirectory.

---

CHANGELOG.md
src/html/html-script-tag.ts
src/javascript/javascript-export-scanner.ts
src/javascript/javascript-import-scanner.ts
src/model/analysis.ts
src/model/document.ts
src/model/import.ts
src/model/reference.ts
src/test/core/analyzer_test.ts
src/test/html/html-script-scanner_test.ts
src/test/static/javascript/module.js

Import features will now be produced when a document has a broken import

---

CHANGELOG.md
package-lock.json
package.json
src/polymer/behavior-scanner.ts
src/test/polymer/behavior-scanner_test.ts
src/test/static/exported-behaviors.js
src/test/static/uses-behaviors.js

Also cleans up some super sketchy code that was almost definitely silently crashing on some code.

Support behaviors declared in export statements.

---

CHANGELOG.md
custom_typings/whatwg-url.d.ts
src/javascript/javascript-import-scanner.ts
src/javascript/resolve-specifier-node.ts
src/test/javascript/javascript-import-scanner_test.ts
src/test/polymer/dom-module-scanner_test.ts
src/test/static/javascript/module-with-named-import.js

Extract node module resolution from JavascriptImport into a separate module

---

src/javascript/javascript-export-scanner.ts
src/test/javascript/javascript-export-scanner_test.ts
src/test/static/javascript/all-export-types.js
src/test/static/javascript/module-with-export-and-default-export.js

Fixes https://github.com/Polymer/polymer-analyzer/issues/930

Fixed issue with `export * from` where it incorrectly re-exported `default` exports.

---

CHANGELOG.md

Prepare 3.0.0-pre.18

---

CHANGELOG.md
gulpfile.js
package-lock.json
package.json
src/warning/warning-filter.ts

Remove dependency on polymer-project-config.

---

CHANGELOG.md
src/core/analysis-context.ts
src/core/analyzer.ts
src/core/async-work-cache.ts
src/core/cancel-token.ts
src/test/core/analyzer_test.ts
src/test/core/cancelling-analysis_test.ts
src/test/test-utils.ts
src/test/typescript/typescript-analyzer_test.ts

Add the ability to cancel an analysis

---

CHANGELOG.md
package-lock.json
src/javascript/javascript-parser.ts
src/test/javascript/javascript-parser_test.ts

Add import.meta parsing support

---

CHANGELOG.md

Prepare 3.0.0-pre.20 release.

---

src/javascript/javascript-import-scanner.ts

Clarify module specifier warning.

---

CHANGELOG.md

Prepare 3.0.0-pre.21 release.
